  <div id="footer" class="row">
    <div class="four columns">
      <p>© 2012 Alert Site</p>
    </div>
    <div class="eight columns">
      <ul class="inline-list right">
        <li><a href="#">About</a></li>
        <li><a href="#">Help</a></li>
        <li><a href="#">Disclaimer</a></li>
        <li><a href="#">Advertise</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>