  <div id="header" class="row">
    <div class="seven columns">
        <h2>AlertSite.com</h2>
        <p>Draft version <strong>0.0.1</strong> generated on December 2012.</p>
    </div>
    
    <div class="five columns">
      <div class="row collapse">
        <div class="eight mobile-three columns">
          <input type="text" />
        </div>
        <div class="four mobile-one columns">
          <a href="#" class="postfix button expand">Search</a>
        </div>
      </div>
      <div id="menu-locale-container">
        <div id="locale">
          <a href="<?php echo $this->url(array('module' => 'default',
                                               'controller' => 'locale', 'action' => 'index',
                                               'locale' => 'en_US'), 'default', true); ?>">
￼￼            <img src="/images/flags/203.png" /></a>
          <a href="<?php echo $this->url(array('module' => 'default',
                                               'controller' => 'locale', 'action' => 'index',
                                               'locale' => 'es_ES'), 'default', true); ?>">
            <img src="/images/flags/176.png" /></a>
        </div>
      </div>
    </div>
  </div>