<div class="row">
	<div class="seven columns">
		<h4><?php echo $this->translate('Scoreboard');?></h4>
	</div>
	<div class="five columns">
		<p class="right"><a href="#">Previous Day</a>  |  Tue, Aug 2, 2012  |  <a href="#">Next Day</a></p>
	</div>
</div>

<div class="row">
	<div class="nine columns">
		<ul class="accordion"class="support tag close">
		  <li class="active">
		    <div class="title">
		      <h5>Americas - Copa Libertadores</h5>
		    </div>
		    <div class="content">
		      <table class="twelve">
		        <tbody>
		          <tr>
		            <td>Team Name</td>
		            <td>vs</td>
		            <td>Team Name</td>
		            <td>HH:MM</td>
		            <td>Details</td>
		          </tr>
		          <tr>
		            <td>Team Name</td>
		            <td>vs</td>
		            <td>Team Name</td>
		            <td>Playing 87'</td>
		            <td>Details</td>
		          </tr>
		           <tr>
		            <td>Team Name</td>
		            <td>vs</td>
		            <td>Team Name</td>
		            <td>Finals</td>
		            <td>Details</td>
		          </tr>
		        </tbody>
		      </table>
		    </div>
		  </li>
		  <li>
		    <div class="title">
		      <h5>England FA Cup</h5>
		    </div>
		    <div class="content">
		       <table class="twelve">
		        <tbody>
		          <tr>
		            <td>Team Name</td>
		            <td>vs</td>
		            <td>Team Name</td>
		            <td>HH:MM</td>
		            <td>Details</td>
		          </tr>
		        </tbody>
		      </table>
		    </div>
		  </li>
		  <li>
		    <div class="title">
		      <h5>Spain - Copa del Rey</h5>
		    </div>
		    <div class="content">
		       <table class="twelve">
		        <tbody>
		          <tr>
		            <td>Team Name</td>
		            <td>vs</td>
		            <td>Team Name</td>
		            <td>HH:MM</td>
		            <td>Details</td>
		          </tr>
		        </tbody>
		      </table>
		    </div>
		  </li>
		</ul>
	</div>
	<div class="three columns">
	
	</div>
</div>
