<?php

return array(
    // outer template
    'Home-Text'=>'Follow your favorite players, teams, leagues & tournaments around the world with updates from AlertSite.com',
	'Home-Text2'=>'It\'s fun and free. Sign up now.',
	'Sign-In'=>'Sign In',
	'Sign-Out'=>'Sign Out',
	'Sign-Up'=>'Sign up',
	'Messages'=>'Messages',
	'Help'=>'Help/FAQ',
	'Feedback'=>'Feedback',
	'Search-Text'=>'Search GoalFace...',
	'Search'=>'Search',
	'Home'=>'Home',
    'Scores-Schedules'=>'Scores &amp; Schedules',
   	'News'=>'News',
	'Pictures'=>'Pictures',
    'Teams'=>'Teams',
    'Players'=>'Players',
    'Leagues-Tournaments'=>'Leagues & Tournament',
    'Fan-Profiles'=>'Fan Profiles',
	'Make-This-My-Homepage'=>'Make This My Homepage',
	'Invite-Friends'=>'Invite Friends',
	'Email-This-Page'=>'Email This Page',
	'Language'=>'Language Options',
	'Join-the-fun'=>'Join the Fun',
	'Free'=>'free',
	'Member'=>'Already a member?',
	'Draw'=> 'registered a draw against',
	//Sign In
	'Sign-in-to-GoalFace' => 'Sign in to GoalFace',
	'Feedback' => 'Feedback',
	'Feedback-Title1' =>'Tell us what you think',
	'Feedback-Title2' => 'about GoalFace.  We\'d love to hear what you have to say.',
	'Feedback-Teams-Players' => 'Featured Teams &amp; Players',
	'More' => 'More',
	'Teams' => 'Teams',
	'Players' => 'Players',
	'See-More-Featured-Teams' => 'See More Featured Teams',
	'See-More-Featured-Players' => 'See More Featured Players',
	'Show' => 'Show:',
	'All-Activity'=> 'All Activity',
	'Friends'=> 'Friends',
	'Teams'=> 'Teams',
	'Players'=> 'Players',
	'News'=> 'News',
	'Subscribe'=> 'Subscribe',
	'Top News'=>'Top News',
	'Show'=>'Show',
	'Headlines'=>'Headlines',
	'News'=> 'News',
	'from-around-the-world'=> 'from around the world',
	'Football' =>'Football',
	'See'=>'See',
	'Pictures'=>'Pictures',
	'Display'=>'Display',
	'Photos'=>'Photos',
	'Ok'=>'Ok',
	'Scoreboard'=>'Scoreboard',
	'My'=>'My',
	'Scores'=>'Scores',
	'Schedules'=>'Schedules',
	'Today'=>'Today',
	'Last'=>'Last',
	'Days'=>'Days',
	'Tomorrow'=>'Tomorrow',
	'Next'=>'Next',
	'Featured'=>'Featured'
);

